backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Type", name: "type", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: Summary 164-220, name: summary, widget: text, required: true, pattern: ['.{164,220}', "Must be within 164 and 220 characters"]}
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Updated Date", name: "update", widget: "date", required: false}
      - {label: "Author", name: "author", widget: "string", required: true}
      - {label: "Author Link", name: "authorlink", widget: "string", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Type", name: "type", widget: "string", required: false}
      - {label: "Office Name", name: "office_name", widget: "string", required: true}
      - {label: "Office Link", name: "office_link", widget: "string", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Job Summary", name: summary, widget: text, required: true}
      - {label: "Job Description", name: "body", widget: "markdown", required: true}
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Updated Date", name: "update", widget: "date", required: false}
      - {label: "Source Name", name: "source_name", widget: "string", required: false}
      - {label: "Original Link", name: "source_url", widget: "string", required: false}
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Type", name: "type", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Summary", name: summary, widget: text, required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Source Name", name: "source_name", widget: "string", required: false}
      - {label: "Original Link", name: "source_url", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Updated Date", name: "update", widget: "date", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
