backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
show_preview_link: true
display_url: https://ban.netlify.com
logo_url: https://ban.netlify.com/logo_ban.png
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Type", name: "type", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: Summary 164-220, name: summary, widget: text, required: true, pattern: ['.{164,220}', "Must be within 164 and 220 characters"]}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Author", name: "author", widget: "string", required: true}
      - {label: "Author Link", name: "authorlink", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Updated Date", name: "update", widget: "datetime", required: false}
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Type", name: "type", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: Summary 164-220, name: summary, widget: text, required: true, pattern: ['.{164,220}', "Must be within 164 and 220 characters"]}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Author", name: "author", widget: "string", required: true}
      - {label: "Author Link", name: "authorlink", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Updated Date", name: "update", widget: "datetime", required: false}
  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Type", name: "type", widget: "string", required: false}
      - {label: "Office Name", name: "office_name", widget: "string", required: true}
      - {label: "Office Link", name: "office_link", widget: "string", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Job Summary", name: summary, widget: text, required: true}
      - {label: "Job Description", name: "body", widget: "markdown", required: true}
      - {label: "Source Name", name: "source_name", widget: "string", required: false}
      - {label: "Original Link", name: "source_url", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Updated Date", name: "update", widget: "datetime", required: false}
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Type", name: "type", widget: "string", required: false, hint: "Exhibition Opening, Meetup, Seminar, Talk, etc."}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", required: true, dateFormat: "DD.MM.YY", timeFormat: "HH:MM"}
      - {label: "Venue", name: "venue", widget: "string", required: true}
      - {label: "Link", name: "url", widget: "string", required: false, hint: Link to the venue or directly to the event page.}
      - {label: "Summary", name: summary, widget: text, required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Publish Date", name: "publish_date", widget: "datetime", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
